# Generated by Django 3.2 on 2025-03-31 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=20, unique=True)),
                ('policy_type', models.CharField(choices=[('life', 'Life Insurance'), ('health', 'Health Insurance'), ('auto', 'Auto Insurance'), ('home', 'Home Insurance'), ('travel', 'Travel Insurance'), ('business', 'Business Insurance')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('premium_amount', models.DecimalField(decimal_places=2, help_text='Amount per payment period', max_digits=10)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semi-Annual'), ('annual', 'Annual')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('deductible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beneficiaries', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='accounts.account')),
                ('policy_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('creation', 'Policy Creation'), ('update', 'Policy Update'), ('cancellation', 'Policy Cancellation'), ('renewal', 'Policy Renewal'), ('payment', 'Premium Payment'), ('payment_failed', 'Failed Payment'), ('claim_filed', 'Claim Filed'), ('claim_approved', 'Claim Approved'), ('claim_rejected', 'Claim Rejected'), ('claim_paid', 'Claim Paid')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='insurance.insurancepolicy')),
            ],
            options={
                'verbose_name_plural': 'Policy Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='insurance.insurancepolicy')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('filed_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('processing', 'Processing Payment'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('documents', models.TextField(blank=True, help_text='Document references')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.insurancepolicy')),
            ],
        ),
    ]
